
const LS='tlb_marketing_os_v2';
const defaultData={calendar:[],research:[],packs:[],stories:[],directory:[],mission:{},settings:{supabaseUrl:'',supabaseAnonKey:'',functionName:'generate-content'},brand:{company:'The Lead Boss',email:'ariana@theleadboss.com',core:'Your agents sell. We deliver opportunities.',offer:'Premium Medicare live transfers, lead generation support, agency growth consulting, pilot programs, and scalable daily volume for agencies that need consistent conversations.',icp:'Medicare agencies, FMOs, IMOs, insurance organizations, and call centers with multiple licensed agents, active lead budgets, and capacity for 50–120+ live transfers per day.',tone:'Bright, premium, confident, helpful, agency-focused, compliant, clear, growth-minded, not spammy, not desperate.',avoid:'Avoid: cheap leads, guaranteed sales, unrealistic claims, aggressive compliance claims, spam language, copying competitor wording, pretending to be a customer if that is not true. For Reddit/Facebook, be transparent and useful; mention The Lead Boss softly only where natural.'}};
let data=load();let calendar;
let uploadCache={source:[],story:[],comment:[]};
function load(){try{return {...defaultData,...JSON.parse(localStorage.getItem(LS)||'{}')}}catch(e){return defaultData}}
function save(){localStorage.setItem(LS,JSON.stringify(data));refreshMetrics();}
function showModal(t){document.getElementById('modalText').textContent=t;document.getElementById('copyModal').classList.add('show');navigator.clipboard?.writeText(t).catch(()=>{});}function closeModal(){document.getElementById('copyModal').classList.remove('show')}

document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.page).classList.add('active');if(b.dataset.page==='calendar') setTimeout(()=>calendar?.render(),50)}));
const missions=['LinkedIn authority post','Facebook post','Instagram carousel','Short-form video script','YouTube Short','Industry insight','15 Facebook comments','10 LinkedIn comments','5 Reddit contributions','Engage with 5 agency owners'];
function renderMission(){const box=document.getElementById('missionList');box.innerHTML='';missions.forEach((m,i)=>{const id='m'+i;box.innerHTML+=`<label class="check" style="margin:0;text-transform:none;letter-spacing:0;color:var(--ink);font-size:14px"><input type="checkbox" ${data.mission[id]?'checked':''} onchange="data.mission['${id}']=this.checked;save();renderMission()"><span>${m}</span></label>`});const done=Object.values(data.mission).filter(Boolean).length;const pct=Math.round(done/missions.length*100);document.getElementById('progressBar').style.width=pct+'%';document.getElementById('progressText').textContent=pct+'%'}
function resetMission(){data.mission={};save();renderMission()}
function refreshMetrics(){document.getElementById('metricCalendar').textContent=data.calendar.length;document.getElementById('metricResearch').textContent=data.research.length;document.getElementById('metricStories').textContent=data.stories.length;document.getElementById('metricPacks').textContent=data.packs.length}
function statusClass(status){return 'status-'+String(status||'Idea').replaceAll(' ','-').replaceAll('/','-')}
function calendarEvents(){return data.calendar.map(x=>({id:x.id,title:`${x.platform}: ${x.title}`,start:x.date,className:[statusClass(x.status)],extendedProps:x}))}
function refreshCalendar(){if(calendar){calendar.removeAllEvents();calendarEvents().forEach(e=>calendar.addEvent(e));calendar.render();}}
function initCalendar(){const el=document.getElementById('contentCalendar');calendar=new FullCalendar.Calendar(el,{initialView:'dayGridMonth',height:'auto',events:calendarEvents(),eventClick(info){openCalendarEditor(info.event.id)}});calendar.render()}
function addCalendarItem(){const title=val('calTitle'),date=val('calDate');if(!title||!date)return alert('Add title and date.');data.calendar.push({id:Date.now()+'',title,date,platform:val('calPlatform'),type:val('calType'),status:val('calStatus'),asset:'',notes:''});save();document.getElementById('calTitle').value='';refreshCalendar();}
function openCalendarEditor(id){const item=data.calendar.find(x=>x.id===id);if(!item)return;document.getElementById('editCalId').value=item.id;document.getElementById('editCalTitle').value=item.title||'';document.getElementById('editCalDate').value=item.date||'';document.getElementById('editCalPlatform').value=item.platform||'LinkedIn';document.getElementById('editCalType').value=item.type||'Authority Post';document.getElementById('editCalStatus').value=item.status||'Idea';document.getElementById('editCalAsset').value=item.asset||'';document.getElementById('editCalNotes').value=item.notes||'';document.getElementById('calendarEditModal').classList.add('show')}
function closeCalendarEditor(){document.getElementById('calendarEditModal').classList.remove('show')}
function saveCalendarEdit(){const id=val('editCalId');const item=data.calendar.find(x=>x.id===id);if(!item)return;item.title=val('editCalTitle');item.date=val('editCalDate');item.platform=val('editCalPlatform');item.type=val('editCalType');item.status=val('editCalStatus');item.asset=val('editCalAsset');item.notes=val('editCalNotes');if(!item.title||!item.date)return alert('Title and date are required.');save();refreshCalendar();closeCalendarEditor()}
function duplicateCalendarItem(){const id=val('editCalId');const item=data.calendar.find(x=>x.id===id);if(!item)return;const copy={...item,id:Date.now()+'',title:item.title+' (copy)',status:'Idea'};data.calendar.push(copy);save();refreshCalendar();openCalendarEditor(copy.id)}
function deleteCalendarItem(){const id=val('editCalId');if(!confirm('Delete this calendar item?'))return;data.calendar=data.calendar.filter(x=>x.id!==id);save();refreshCalendar();closeCalendarEditor()}
function val(id){return document.getElementById(id).value.trim()}
const assetNames=['LinkedIn Authority Post','Facebook Post','Instagram Carousel','Reel / Short Script','YouTube Short','Industry Insight','Comment Question','Blog Outline','ChatGPT Visual Prompt','ElevenLabs Prompt','HeyGen Prompt','Calendar Suggestions'];
function buildPrompt(mode){const brand=data.brand;return `You are The Lead Boss content strategist. Do not copy competitor wording. Extract the topic, pain point, hook, and structure, then create original content for Medicare agency owners, FMOs, IMOs, and call centers.\n\nBRAND CONTEXT:\nCompany: ${brand.company}\nEmail: ${brand.email}\nCore Message: ${brand.core}\nOffer: ${brand.offer}\nIdeal Customer: ${brand.icp}\nTone: ${brand.tone}\nGuardrails: ${brand.avoid}\n\nTASK: ${mode==='campaign'?'Create a full weekly campaign plan from this source.':'Create a complete daily content pack from this source.'}\n\nSOURCE NAME: ${val('sourceName')}\nPLATFORM: ${val('sourcePlatform')}\nLINK: ${val('sourceLink')}\nTEXT/TRANSCRIPT/ARTICLE/NOTES:\n${val('sourceText')}\n\nVISUAL/SCREENSHOT NOTES:\n${val('sourceVisual')}\n\nATTACHED IMAGE COUNT: ${uploadCache.source.length}\nIf images are attached, analyze the visible layout, hook, style, offer, and positioning without copying it.\n\nOUTPUT REQUIRED:\n- Original Lead Boss angle\n- LinkedIn authority post\n- Facebook post\n- Instagram carousel copy\n- Reel/Short script\n- YouTube Short title + caption\n- Industry insight\n- Engagement question\n- Blog outline\n- ChatGPT image prompt\n- ElevenLabs voice prompt\n- HeyGen avatar prompt\n- Suggested calendar placement\n\nKeep it premium, useful, agency-owner focused, and authentic.`}
function buildPayload(mode){return {mode,brand:data.brand,source:{name:val('sourceName')||'Untitled Source',platform:val('sourcePlatform'),link:val('sourceLink'),text:val('sourceText'),visual:val('sourceVisual')},images:uploadCache.source.map(x=>({name:x.name,type:x.type,dataUrl:x.dataUrl}))}}
async function generatePack(mode){
  const prompt=buildPrompt(mode);
  const pack={id:Date.now()+'',date:new Date().toLocaleString(),source:val('sourceName')||'Untitled Source',prompt,assets:null};
  const researchItem={id:Date.now()+'r',date:new Date().toLocaleString(),source:pack.source,platform:val('sourcePlatform'),link:val('sourceLink'),text:val('sourceText').slice(0,500),visual:val('sourceVisual').slice(0,500),photos:uploadCache.source.map(x=>({name:x.name,type:x.type,dataUrl:x.dataUrl}))};
  try{
    const ai=await callAI(mode);
    pack.assets=ai.assets||ai;
    data.packs.unshift(pack);data.research.unshift(researchItem);save();renderAssetsFromAI(pack.assets);renderResearch();showModal(typeof ai.raw==='string'?ai.raw:JSON.stringify(pack.assets,null,2));
  }catch(err){
    data.packs.unshift(pack);data.research.unshift(researchItem);save();renderAssets(prompt);renderResearch();showModal(prompt+'\n\n---\nBackend not connected or returned an error. Copy this master prompt into ChatGPT.\nError: '+err.message);
  }
}
async function callAI(mode){
  const st=data.settings||{};
  if(!st.supabaseUrl||!st.supabaseAnonKey) throw new Error('Supabase backend settings are missing.');
  const url=st.supabaseUrl.replace(/\/$/,'')+'/functions/v1/'+(st.functionName||'generate-content');
  const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+st.supabaseAnonKey,'apikey':st.supabaseAnonKey},body:JSON.stringify(buildPayload(mode))});
  if(!res.ok){throw new Error(await res.text())}
  return await res.json();
}
function copyMasterPrompt(mode){showModal(buildPrompt(mode))}
function renderAssetsFromAI(assets){
  const box=document.getElementById('assetBucket');box.innerHTML='';
  const map=Array.isArray(assets)?assets:Object.entries(assets||{}).map(([title,content])=>({title,content:typeof content==='string'?content:JSON.stringify(content,null,2)}));
  (map.length?map:assetNames.map(title=>({title,content:''}))).forEach(a=>{box.innerHTML+=`<div class="asset-card"><h4>${escapeHtml(a.title||'Asset')}</h4><textarea>${escapeHtml(a.content||'')}</textarea><button class="btn secondary small" onclick="navigator.clipboard.writeText(this.previousElementSibling.value)">Copy</button></div>`})
}
function renderAssets(prompt=''){const box=document.getElementById('assetBucket');box.innerHTML='';assetNames.forEach(name=>{box.innerHTML+=`<div class="asset-card"><h4>${name}</h4><textarea placeholder="AI output appears here after backend generation or after you paste the master prompt into ChatGPT.">${prompt?`Use the master prompt to generate: ${name}`:''}</textarea><button class="btn secondary small" onclick="navigator.clipboard.writeText(this.previousElementSibling.value)">Copy</button></div>`})}
function escapeHtml(str){return String(str).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function handlePhotoUpload(event, bucket){
  const files=[...event.target.files].slice(0,6);
  uploadCache[bucket]=[];
  Promise.all(files.map(file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({name:file.name,type:file.type,size:file.size,dataUrl:r.result});r.onerror=reject;r.readAsDataURL(file)}))).then(items=>{uploadCache[bucket]=items;renderPhotoPreview(bucket)}).catch(()=>alert('Could not read one of the images.'))
}
function renderPhotoPreview(bucket){
  const el=document.getElementById(bucket+'PhotoPreview');if(!el)return;
  el.innerHTML=uploadCache[bucket].map(x=>`<div class="photo-tile"><img src="${x.dataUrl}" alt="${escapeHtml(x.name)}"><p>${escapeHtml(x.name)}</p></div>`).join('')
}
function saveResearchOnly(){data.research.unshift({id:Date.now()+'',date:new Date().toLocaleString(),source:val('sourceName')||'Untitled Source',platform:val('sourcePlatform'),link:val('sourceLink'),text:val('sourceText'),visual:val('sourceVisual'),photos:uploadCache.source.map(x=>({name:x.name,type:x.type,dataUrl:x.dataUrl}))});save();renderResearch()}
function renderResearch(){const el=document.getElementById('researchList');el.innerHTML=data.research.length?'':'<div class="empty">No research saved yet.</div>';data.research.forEach(x=>el.innerHTML+=`<div class="item"><div class="item-head"><div><h4>${x.source}</h4><p>${x.platform} • ${x.date}</p>${x.link?`<p><a href="${x.link}" target="_blank">Open Source</a></p>`:''}<p>${(x.text||'').slice(0,220)}</p>${x.photos&&x.photos.length?`<div class="photo-grid">${x.photos.slice(0,4).map(p=>`<div class="photo-tile"><img src="${p.dataUrl}"><p>${escapeHtml(p.name||'photo')}</p></div>`).join('')}</div>`:''}</div><span class="status">Research</span></div></div>`) }
function copyAllAssets(){const text=[...document.querySelectorAll('#assetBucket textarea')].map(t=>t.value).join('\n\n---\n\n');showModal(text||'No assets yet.')}
function addStory(){if(!val('storyTitle'))return alert('Add a title.');data.stories.unshift({id:Date.now()+'',date:new Date().toLocaleString(),type:val('storyType'),title:val('storyTitle'),details:val('storyDetails'),photos:uploadCache.story.map(x=>({name:x.name,type:x.type,dataUrl:x.dataUrl}))});save();renderStories();document.getElementById('storyTitle').value='';document.getElementById('storyDetails').value=''}
function renderStories(){const el=document.getElementById('storyList');el.innerHTML=data.stories.length?'':'<div class="empty">No stories saved yet.</div>';data.stories.forEach(x=>el.innerHTML+=`<div class="item"><div class="item-head"><div><h4>${x.title}</h4><p>${x.type} • ${x.date}</p><p>${x.details.slice(0,260)}</p></div><span class="status">Story</span></div></div>`)}
function generateFromStory(){const latest=data.stories[0]||{title:val('storyTitle'),type:val('storyType'),details:val('storyDetails')};showModal(`Turn this story into: LinkedIn post, Facebook post, Instagram carousel, Reel script, Reddit comment, and blog outline.\n\nBrand: ${data.brand.company}\nTone: ${data.brand.tone}\nStory Type: ${latest.type}\nTitle: ${latest.title}\nDetails: ${latest.details}\n\nDo not overclaim. Make it helpful and agency-owner focused.`)}
function generateComments(){const platform=val('commentPlatform'),input=val('commentInput');const buckets={
'Helpful Reply':`A useful, non-salesy reply for ${platform}:\n\nA lot of agencies run into this when they focus on lead count instead of conversation quality. One strong filter is asking: will this source actually increase agent talk time, or just add more names to chase?`,
'Thought Leadership':`Authority-building reply for ${platform}:\n\nThe hidden issue is usually operations, not just marketing. If the agency cannot handle consistent transfer volume, even a good lead source gets wasted. Capacity and follow-up matter as much as lead flow.`,
'Soft Lead Boss Mention':`Soft mention for ${platform}:\n\nWe've seen The Lead Boss positioned more for agencies that need meaningful transfer volume rather than solo-agent lead buying. Worth looking at if the operation can actually handle scale.`,
'Follow-Up Question':`Follow-up question for ${platform}:\n\nAre you trying to increase total lead volume, or are you trying to get your agents into more real conversations each day? Those are two different problems.`,
'Reddit Careful Reply':`Careful Reddit-style reply:\n\nI would be cautious with any vendor until you know your close rate, daily capacity, and return per call. Larger Medicare teams usually need transfer volume, but solo agents may be better off optimizing follow-up first.`
};document.getElementById('commentBank').innerHTML=Object.entries(buckets).map(([k,v])=>`<div class="comment-card"><h4>${k}</h4><textarea>${v}\n\nContext used: ${input.slice(0,180)}</textarea><button class="btn secondary small" onclick="navigator.clipboard.writeText(this.previousElementSibling.value)">Copy</button></div>`).join('')}
function copyCommentBank(){showModal([...document.querySelectorAll('#commentBank textarea')].map(x=>x.value).join('\n\n---\n\n')||'No comments generated yet.')}
function saveBrand(){data.brand={company:val('brandCompany'),email:val('brandEmail'),core:val('brandCore'),offer:val('brandOffer'),icp:val('brandICP'),tone:val('brandTone'),avoid:val('brandAvoid')};save();alert('Brand Brain saved.')}
function fillBrand(){document.getElementById('brandCompany').value=data.brand.company;document.getElementById('brandEmail').value=data.brand.email;document.getElementById('brandCore').value=data.brand.core;document.getElementById('brandOffer').value=data.brand.offer;document.getElementById('brandICP').value=data.brand.icp;document.getElementById('brandTone').value=data.brand.tone;document.getElementById('brandAvoid').value=data.brand.avoid;document.getElementById('setSupabaseUrl').value=(data.settings||{}).supabaseUrl||'';document.getElementById('setSupabaseAnon').value=(data.settings||{}).supabaseAnonKey||'';document.getElementById('setFunctionName').value=(data.settings||{}).functionName||'generate-content'}
function saveSettings(){data.settings={supabaseUrl:val('setSupabaseUrl'),supabaseAnonKey:val('setSupabaseAnon'),functionName:val('setFunctionName')||'generate-content'};save();alert('Backend settings saved.')}
function addDirectory(){if(!val('dirName'))return alert('Add a link name.');data.directory.unshift({id:Date.now()+'',name:val('dirName'),url:val('dirUrl'),notes:val('dirNotes')});save();renderDirectory();document.getElementById('dirName').value='';document.getElementById('dirUrl').value='';document.getElementById('dirNotes').value=''}
function renderDirectory(){const el=document.getElementById('directoryList');el.innerHTML=data.directory.length?'':'<div class="empty">No links saved yet.</div>';data.directory.forEach(x=>el.innerHTML+=`<div class="item"><div class="item-head"><div><h4>${x.name}</h4>${x.url?`<p><a href="${x.url}" target="_blank">${x.url}</a></p>`:''}<p>${x.notes}</p></div><span class="status">SOP</span></div></div>`)}
function clearList(type){if(confirm('Clear this list?')){data[type]=[];save();renderResearch();renderStories();renderDirectory();}}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tlb-marketing-os-backup.json';a.click()}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);save();location.reload()}catch(err){alert('Invalid JSON')}};r.readAsText(f)}
function seedDirectory(){if(data.directory.length)return;data.directory=[{name:'Meta Business Suite',url:'',notes:'Schedule Facebook and Instagram posts/reels. Save final captions in the calendar item before scheduling.'},{name:'LinkedIn Company Page',url:'',notes:'Schedule authority posts and articles. Use agency-owner tone, not consumer tone.'},{name:'YouTube Studio',url:'',notes:'Upload Shorts and videos. Include keywords: Medicare live transfers, Medicare lead generation, agency growth.'},{name:'Canva Folder',url:'',notes:'Store carousels, post graphics, covers, and brand assets.'},{name:'ElevenLabs',url:'',notes:'Paste voice prompt from AI Factory. Use one consistent brand voice.'},{name:'HeyGen',url:'',notes:'Paste avatar prompt. Keep the same business-casual host for brand familiarity.'}];save()}
function boot(){renderMission();refreshMetrics();fillBrand();seedDirectory();renderDirectory();renderResearch();renderStories();renderAssets();initCalendar();}
boot();
